language: javascript
before_install:
- openssl aes-256-cbc -K $encrypted_5b89ab2dea96_key -iv $encrypted_5b89ab2dea96_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.106.58.139\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: npm install
script: npm run build
after_success:
- ssh root@39.106.58.139
- scp -o StrictHostKeyChecking=no ./dist/ :/root/palaispaEcateVue
