export const SET_VIDEO = "SET_VIDEO";

export const SET_VIDEOPOSTER = "SET_VIDEOPOSTER";

export const SET_EXHIBITVIDEO = "SET_EXHIBITVIDEO";

export const SET_SHOULD_MAIN_SCROLL_REFRESH = "SET_SHOULD_MAIN_SCROLL_REFRESH";

export const SET_SELECTED_TREATMENT = "SET_SELECTED_TREATMENT";

export const SET_SHOW_TREATMENT_DETAIL = "SET_SHOW_TREATMENT_DETAIL";

export const SET_TREAT_DETAIL_ASIDE = "SET_TREAT_DETAIL_ASIDE";

export const SET_SHOW_POPULARIZE = "SET_SHOW_POPULARIZE";

export const SET_MAIN_BANNER_GENERIZE = "SET_MAIN_BANNER_GENERIZE";

export const SET_SHOW_STORE_DETAIL = "SET_SHOW_STORE_DETAIL";

export const SET_STORE_DETAIL = "SET_STORE_DETAIL";