export const SET_VIDEO = "SET_VIDEO";

export const SET_VIDEOPOSTER = "SET_VIDEOPOSTER";

export const SET_EXHIBITVIDEO = "SET_EXHIBITVIDEO";

export const SET_SHOULD_MAIN_SCROLL_REFRESH = "SET_SHOULD_MAIN_SCROLL_REFRESH";